name: kathleenndongmo
favicon: null
layout_spectrum: 0.6890580211766064
typography_spectrum: 0.8297051207628101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6202583459671587
  lightness: 0.4171920989174396
  saturation: 0.1162963944952935
  rhythmicContrast: 0.7735641205217689
purpose: []
